services:
  database:
    image: postgres:15
    privileged: true
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: haraka_data
    ports:
      - "5432:5432"
    # volumes:
      # - ./postgres_data:/var/lib/postgresql/data
    networks:
      - haraka_network

  grafana:
    image: grafana/grafana-oss:latest
    privileged: true
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # volumes:
      # - ./grafana_data:/var/lib/grafana
    networks:
      - haraka_network
    depends_on:
      database: # condition end
        condition: service_started


networks:
  haraka_network:
    driver: bridge